# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.23

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/cmake-3.23.0-rc5-linux-x86_64/bin/cmake

# The command to remove a file.
RM = /opt/cmake-3.23.0-rc5-linux-x86_64/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/tapsi/codes/cpu-simulation

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/tapsi/codes/cpu-simulation

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/cmake-3.23.0-rc5-linux-x86_64/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/cmake-3.23.0-rc5-linux-x86_64/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tapsi/codes/cpu-simulation/CMakeFiles /home/tapsi/codes/cpu-simulation//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tapsi/codes/cpu-simulation/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cpu_simulation

# Build rule for target.
cpu_simulation: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cpu_simulation
.PHONY : cpu_simulation

# fast build rule for target.
cpu_simulation/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu_simulation.dir/build.make CMakeFiles/cpu_simulation.dir/build
.PHONY : cpu_simulation/fast

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu_simulation.dir/build.make CMakeFiles/cpu_simulation.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu_simulation.dir/build.make CMakeFiles/cpu_simulation.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu_simulation.dir/build.make CMakeFiles/cpu_simulation.dir/main.cpp.s
.PHONY : main.cpp.s

src/domain/arith/ArithUnit.o: src/domain/arith/ArithUnit.cpp.o
.PHONY : src/domain/arith/ArithUnit.o

# target to build an object file
src/domain/arith/ArithUnit.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu_simulation.dir/build.make CMakeFiles/cpu_simulation.dir/src/domain/arith/ArithUnit.cpp.o
.PHONY : src/domain/arith/ArithUnit.cpp.o

src/domain/arith/ArithUnit.i: src/domain/arith/ArithUnit.cpp.i
.PHONY : src/domain/arith/ArithUnit.i

# target to preprocess a source file
src/domain/arith/ArithUnit.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu_simulation.dir/build.make CMakeFiles/cpu_simulation.dir/src/domain/arith/ArithUnit.cpp.i
.PHONY : src/domain/arith/ArithUnit.cpp.i

src/domain/arith/ArithUnit.s: src/domain/arith/ArithUnit.cpp.s
.PHONY : src/domain/arith/ArithUnit.s

# target to generate assembly for a file
src/domain/arith/ArithUnit.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu_simulation.dir/build.make CMakeFiles/cpu_simulation.dir/src/domain/arith/ArithUnit.cpp.s
.PHONY : src/domain/arith/ArithUnit.cpp.s

src/domain/logic/LogicUnit.o: src/domain/logic/LogicUnit.cpp.o
.PHONY : src/domain/logic/LogicUnit.o

# target to build an object file
src/domain/logic/LogicUnit.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu_simulation.dir/build.make CMakeFiles/cpu_simulation.dir/src/domain/logic/LogicUnit.cpp.o
.PHONY : src/domain/logic/LogicUnit.cpp.o

src/domain/logic/LogicUnit.i: src/domain/logic/LogicUnit.cpp.i
.PHONY : src/domain/logic/LogicUnit.i

# target to preprocess a source file
src/domain/logic/LogicUnit.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu_simulation.dir/build.make CMakeFiles/cpu_simulation.dir/src/domain/logic/LogicUnit.cpp.i
.PHONY : src/domain/logic/LogicUnit.cpp.i

src/domain/logic/LogicUnit.s: src/domain/logic/LogicUnit.cpp.s
.PHONY : src/domain/logic/LogicUnit.s

# target to generate assembly for a file
src/domain/logic/LogicUnit.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu_simulation.dir/build.make CMakeFiles/cpu_simulation.dir/src/domain/logic/LogicUnit.cpp.s
.PHONY : src/domain/logic/LogicUnit.cpp.s

src/domain/move/MoveUnit.o: src/domain/move/MoveUnit.cpp.o
.PHONY : src/domain/move/MoveUnit.o

# target to build an object file
src/domain/move/MoveUnit.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu_simulation.dir/build.make CMakeFiles/cpu_simulation.dir/src/domain/move/MoveUnit.cpp.o
.PHONY : src/domain/move/MoveUnit.cpp.o

src/domain/move/MoveUnit.i: src/domain/move/MoveUnit.cpp.i
.PHONY : src/domain/move/MoveUnit.i

# target to preprocess a source file
src/domain/move/MoveUnit.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu_simulation.dir/build.make CMakeFiles/cpu_simulation.dir/src/domain/move/MoveUnit.cpp.i
.PHONY : src/domain/move/MoveUnit.cpp.i

src/domain/move/MoveUnit.s: src/domain/move/MoveUnit.cpp.s
.PHONY : src/domain/move/MoveUnit.s

# target to generate assembly for a file
src/domain/move/MoveUnit.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu_simulation.dir/build.make CMakeFiles/cpu_simulation.dir/src/domain/move/MoveUnit.cpp.s
.PHONY : src/domain/move/MoveUnit.cpp.s

src/domain/shift/ShiftUnit.o: src/domain/shift/ShiftUnit.cpp.o
.PHONY : src/domain/shift/ShiftUnit.o

# target to build an object file
src/domain/shift/ShiftUnit.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu_simulation.dir/build.make CMakeFiles/cpu_simulation.dir/src/domain/shift/ShiftUnit.cpp.o
.PHONY : src/domain/shift/ShiftUnit.cpp.o

src/domain/shift/ShiftUnit.i: src/domain/shift/ShiftUnit.cpp.i
.PHONY : src/domain/shift/ShiftUnit.i

# target to preprocess a source file
src/domain/shift/ShiftUnit.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu_simulation.dir/build.make CMakeFiles/cpu_simulation.dir/src/domain/shift/ShiftUnit.cpp.i
.PHONY : src/domain/shift/ShiftUnit.cpp.i

src/domain/shift/ShiftUnit.s: src/domain/shift/ShiftUnit.cpp.s
.PHONY : src/domain/shift/ShiftUnit.s

# target to generate assembly for a file
src/domain/shift/ShiftUnit.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu_simulation.dir/build.make CMakeFiles/cpu_simulation.dir/src/domain/shift/ShiftUnit.cpp.s
.PHONY : src/domain/shift/ShiftUnit.cpp.s

src/framework/CommandHandler.o: src/framework/CommandHandler.cpp.o
.PHONY : src/framework/CommandHandler.o

# target to build an object file
src/framework/CommandHandler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu_simulation.dir/build.make CMakeFiles/cpu_simulation.dir/src/framework/CommandHandler.cpp.o
.PHONY : src/framework/CommandHandler.cpp.o

src/framework/CommandHandler.i: src/framework/CommandHandler.cpp.i
.PHONY : src/framework/CommandHandler.i

# target to preprocess a source file
src/framework/CommandHandler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu_simulation.dir/build.make CMakeFiles/cpu_simulation.dir/src/framework/CommandHandler.cpp.i
.PHONY : src/framework/CommandHandler.cpp.i

src/framework/CommandHandler.s: src/framework/CommandHandler.cpp.s
.PHONY : src/framework/CommandHandler.s

# target to generate assembly for a file
src/framework/CommandHandler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu_simulation.dir/build.make CMakeFiles/cpu_simulation.dir/src/framework/CommandHandler.cpp.s
.PHONY : src/framework/CommandHandler.cpp.s

src/infrastructure/command/arith/AddCommand.o: src/infrastructure/command/arith/AddCommand.cpp.o
.PHONY : src/infrastructure/command/arith/AddCommand.o

# target to build an object file
src/infrastructure/command/arith/AddCommand.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu_simulation.dir/build.make CMakeFiles/cpu_simulation.dir/src/infrastructure/command/arith/AddCommand.cpp.o
.PHONY : src/infrastructure/command/arith/AddCommand.cpp.o

src/infrastructure/command/arith/AddCommand.i: src/infrastructure/command/arith/AddCommand.cpp.i
.PHONY : src/infrastructure/command/arith/AddCommand.i

# target to preprocess a source file
src/infrastructure/command/arith/AddCommand.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu_simulation.dir/build.make CMakeFiles/cpu_simulation.dir/src/infrastructure/command/arith/AddCommand.cpp.i
.PHONY : src/infrastructure/command/arith/AddCommand.cpp.i

src/infrastructure/command/arith/AddCommand.s: src/infrastructure/command/arith/AddCommand.cpp.s
.PHONY : src/infrastructure/command/arith/AddCommand.s

# target to generate assembly for a file
src/infrastructure/command/arith/AddCommand.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu_simulation.dir/build.make CMakeFiles/cpu_simulation.dir/src/infrastructure/command/arith/AddCommand.cpp.s
.PHONY : src/infrastructure/command/arith/AddCommand.cpp.s

src/infrastructure/command/arith/DivCommand.o: src/infrastructure/command/arith/DivCommand.cpp.o
.PHONY : src/infrastructure/command/arith/DivCommand.o

# target to build an object file
src/infrastructure/command/arith/DivCommand.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu_simulation.dir/build.make CMakeFiles/cpu_simulation.dir/src/infrastructure/command/arith/DivCommand.cpp.o
.PHONY : src/infrastructure/command/arith/DivCommand.cpp.o

src/infrastructure/command/arith/DivCommand.i: src/infrastructure/command/arith/DivCommand.cpp.i
.PHONY : src/infrastructure/command/arith/DivCommand.i

# target to preprocess a source file
src/infrastructure/command/arith/DivCommand.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu_simulation.dir/build.make CMakeFiles/cpu_simulation.dir/src/infrastructure/command/arith/DivCommand.cpp.i
.PHONY : src/infrastructure/command/arith/DivCommand.cpp.i

src/infrastructure/command/arith/DivCommand.s: src/infrastructure/command/arith/DivCommand.cpp.s
.PHONY : src/infrastructure/command/arith/DivCommand.s

# target to generate assembly for a file
src/infrastructure/command/arith/DivCommand.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu_simulation.dir/build.make CMakeFiles/cpu_simulation.dir/src/infrastructure/command/arith/DivCommand.cpp.s
.PHONY : src/infrastructure/command/arith/DivCommand.cpp.s

src/infrastructure/command/arith/MulCommand.o: src/infrastructure/command/arith/MulCommand.cpp.o
.PHONY : src/infrastructure/command/arith/MulCommand.o

# target to build an object file
src/infrastructure/command/arith/MulCommand.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu_simulation.dir/build.make CMakeFiles/cpu_simulation.dir/src/infrastructure/command/arith/MulCommand.cpp.o
.PHONY : src/infrastructure/command/arith/MulCommand.cpp.o

src/infrastructure/command/arith/MulCommand.i: src/infrastructure/command/arith/MulCommand.cpp.i
.PHONY : src/infrastructure/command/arith/MulCommand.i

# target to preprocess a source file
src/infrastructure/command/arith/MulCommand.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu_simulation.dir/build.make CMakeFiles/cpu_simulation.dir/src/infrastructure/command/arith/MulCommand.cpp.i
.PHONY : src/infrastructure/command/arith/MulCommand.cpp.i

src/infrastructure/command/arith/MulCommand.s: src/infrastructure/command/arith/MulCommand.cpp.s
.PHONY : src/infrastructure/command/arith/MulCommand.s

# target to generate assembly for a file
src/infrastructure/command/arith/MulCommand.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu_simulation.dir/build.make CMakeFiles/cpu_simulation.dir/src/infrastructure/command/arith/MulCommand.cpp.s
.PHONY : src/infrastructure/command/arith/MulCommand.cpp.s

src/infrastructure/command/arith/SubCommand.o: src/infrastructure/command/arith/SubCommand.cpp.o
.PHONY : src/infrastructure/command/arith/SubCommand.o

# target to build an object file
src/infrastructure/command/arith/SubCommand.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu_simulation.dir/build.make CMakeFiles/cpu_simulation.dir/src/infrastructure/command/arith/SubCommand.cpp.o
.PHONY : src/infrastructure/command/arith/SubCommand.cpp.o

src/infrastructure/command/arith/SubCommand.i: src/infrastructure/command/arith/SubCommand.cpp.i
.PHONY : src/infrastructure/command/arith/SubCommand.i

# target to preprocess a source file
src/infrastructure/command/arith/SubCommand.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu_simulation.dir/build.make CMakeFiles/cpu_simulation.dir/src/infrastructure/command/arith/SubCommand.cpp.i
.PHONY : src/infrastructure/command/arith/SubCommand.cpp.i

src/infrastructure/command/arith/SubCommand.s: src/infrastructure/command/arith/SubCommand.cpp.s
.PHONY : src/infrastructure/command/arith/SubCommand.s

# target to generate assembly for a file
src/infrastructure/command/arith/SubCommand.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu_simulation.dir/build.make CMakeFiles/cpu_simulation.dir/src/infrastructure/command/arith/SubCommand.cpp.s
.PHONY : src/infrastructure/command/arith/SubCommand.cpp.s

src/infrastructure/command/logic/AndCommand.o: src/infrastructure/command/logic/AndCommand.cpp.o
.PHONY : src/infrastructure/command/logic/AndCommand.o

# target to build an object file
src/infrastructure/command/logic/AndCommand.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu_simulation.dir/build.make CMakeFiles/cpu_simulation.dir/src/infrastructure/command/logic/AndCommand.cpp.o
.PHONY : src/infrastructure/command/logic/AndCommand.cpp.o

src/infrastructure/command/logic/AndCommand.i: src/infrastructure/command/logic/AndCommand.cpp.i
.PHONY : src/infrastructure/command/logic/AndCommand.i

# target to preprocess a source file
src/infrastructure/command/logic/AndCommand.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu_simulation.dir/build.make CMakeFiles/cpu_simulation.dir/src/infrastructure/command/logic/AndCommand.cpp.i
.PHONY : src/infrastructure/command/logic/AndCommand.cpp.i

src/infrastructure/command/logic/AndCommand.s: src/infrastructure/command/logic/AndCommand.cpp.s
.PHONY : src/infrastructure/command/logic/AndCommand.s

# target to generate assembly for a file
src/infrastructure/command/logic/AndCommand.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu_simulation.dir/build.make CMakeFiles/cpu_simulation.dir/src/infrastructure/command/logic/AndCommand.cpp.s
.PHONY : src/infrastructure/command/logic/AndCommand.cpp.s

src/infrastructure/command/logic/NotCommand.o: src/infrastructure/command/logic/NotCommand.cpp.o
.PHONY : src/infrastructure/command/logic/NotCommand.o

# target to build an object file
src/infrastructure/command/logic/NotCommand.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu_simulation.dir/build.make CMakeFiles/cpu_simulation.dir/src/infrastructure/command/logic/NotCommand.cpp.o
.PHONY : src/infrastructure/command/logic/NotCommand.cpp.o

src/infrastructure/command/logic/NotCommand.i: src/infrastructure/command/logic/NotCommand.cpp.i
.PHONY : src/infrastructure/command/logic/NotCommand.i

# target to preprocess a source file
src/infrastructure/command/logic/NotCommand.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu_simulation.dir/build.make CMakeFiles/cpu_simulation.dir/src/infrastructure/command/logic/NotCommand.cpp.i
.PHONY : src/infrastructure/command/logic/NotCommand.cpp.i

src/infrastructure/command/logic/NotCommand.s: src/infrastructure/command/logic/NotCommand.cpp.s
.PHONY : src/infrastructure/command/logic/NotCommand.s

# target to generate assembly for a file
src/infrastructure/command/logic/NotCommand.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu_simulation.dir/build.make CMakeFiles/cpu_simulation.dir/src/infrastructure/command/logic/NotCommand.cpp.s
.PHONY : src/infrastructure/command/logic/NotCommand.cpp.s

src/infrastructure/command/logic/OrCommand.o: src/infrastructure/command/logic/OrCommand.cpp.o
.PHONY : src/infrastructure/command/logic/OrCommand.o

# target to build an object file
src/infrastructure/command/logic/OrCommand.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu_simulation.dir/build.make CMakeFiles/cpu_simulation.dir/src/infrastructure/command/logic/OrCommand.cpp.o
.PHONY : src/infrastructure/command/logic/OrCommand.cpp.o

src/infrastructure/command/logic/OrCommand.i: src/infrastructure/command/logic/OrCommand.cpp.i
.PHONY : src/infrastructure/command/logic/OrCommand.i

# target to preprocess a source file
src/infrastructure/command/logic/OrCommand.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu_simulation.dir/build.make CMakeFiles/cpu_simulation.dir/src/infrastructure/command/logic/OrCommand.cpp.i
.PHONY : src/infrastructure/command/logic/OrCommand.cpp.i

src/infrastructure/command/logic/OrCommand.s: src/infrastructure/command/logic/OrCommand.cpp.s
.PHONY : src/infrastructure/command/logic/OrCommand.s

# target to generate assembly for a file
src/infrastructure/command/logic/OrCommand.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu_simulation.dir/build.make CMakeFiles/cpu_simulation.dir/src/infrastructure/command/logic/OrCommand.cpp.s
.PHONY : src/infrastructure/command/logic/OrCommand.cpp.s

src/infrastructure/command/logic/SltCommand.o: src/infrastructure/command/logic/SltCommand.cpp.o
.PHONY : src/infrastructure/command/logic/SltCommand.o

# target to build an object file
src/infrastructure/command/logic/SltCommand.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu_simulation.dir/build.make CMakeFiles/cpu_simulation.dir/src/infrastructure/command/logic/SltCommand.cpp.o
.PHONY : src/infrastructure/command/logic/SltCommand.cpp.o

src/infrastructure/command/logic/SltCommand.i: src/infrastructure/command/logic/SltCommand.cpp.i
.PHONY : src/infrastructure/command/logic/SltCommand.i

# target to preprocess a source file
src/infrastructure/command/logic/SltCommand.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu_simulation.dir/build.make CMakeFiles/cpu_simulation.dir/src/infrastructure/command/logic/SltCommand.cpp.i
.PHONY : src/infrastructure/command/logic/SltCommand.cpp.i

src/infrastructure/command/logic/SltCommand.s: src/infrastructure/command/logic/SltCommand.cpp.s
.PHONY : src/infrastructure/command/logic/SltCommand.s

# target to generate assembly for a file
src/infrastructure/command/logic/SltCommand.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu_simulation.dir/build.make CMakeFiles/cpu_simulation.dir/src/infrastructure/command/logic/SltCommand.cpp.s
.PHONY : src/infrastructure/command/logic/SltCommand.cpp.s

src/infrastructure/command/move/LdimmCommand.o: src/infrastructure/command/move/LdimmCommand.cpp.o
.PHONY : src/infrastructure/command/move/LdimmCommand.o

# target to build an object file
src/infrastructure/command/move/LdimmCommand.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu_simulation.dir/build.make CMakeFiles/cpu_simulation.dir/src/infrastructure/command/move/LdimmCommand.cpp.o
.PHONY : src/infrastructure/command/move/LdimmCommand.cpp.o

src/infrastructure/command/move/LdimmCommand.i: src/infrastructure/command/move/LdimmCommand.cpp.i
.PHONY : src/infrastructure/command/move/LdimmCommand.i

# target to preprocess a source file
src/infrastructure/command/move/LdimmCommand.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu_simulation.dir/build.make CMakeFiles/cpu_simulation.dir/src/infrastructure/command/move/LdimmCommand.cpp.i
.PHONY : src/infrastructure/command/move/LdimmCommand.cpp.i

src/infrastructure/command/move/LdimmCommand.s: src/infrastructure/command/move/LdimmCommand.cpp.s
.PHONY : src/infrastructure/command/move/LdimmCommand.s

# target to generate assembly for a file
src/infrastructure/command/move/LdimmCommand.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu_simulation.dir/build.make CMakeFiles/cpu_simulation.dir/src/infrastructure/command/move/LdimmCommand.cpp.s
.PHONY : src/infrastructure/command/move/LdimmCommand.cpp.s

src/infrastructure/command/move/Mv2MemCommand.o: src/infrastructure/command/move/Mv2MemCommand.cpp.o
.PHONY : src/infrastructure/command/move/Mv2MemCommand.o

# target to build an object file
src/infrastructure/command/move/Mv2MemCommand.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu_simulation.dir/build.make CMakeFiles/cpu_simulation.dir/src/infrastructure/command/move/Mv2MemCommand.cpp.o
.PHONY : src/infrastructure/command/move/Mv2MemCommand.cpp.o

src/infrastructure/command/move/Mv2MemCommand.i: src/infrastructure/command/move/Mv2MemCommand.cpp.i
.PHONY : src/infrastructure/command/move/Mv2MemCommand.i

# target to preprocess a source file
src/infrastructure/command/move/Mv2MemCommand.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu_simulation.dir/build.make CMakeFiles/cpu_simulation.dir/src/infrastructure/command/move/Mv2MemCommand.cpp.i
.PHONY : src/infrastructure/command/move/Mv2MemCommand.cpp.i

src/infrastructure/command/move/Mv2MemCommand.s: src/infrastructure/command/move/Mv2MemCommand.cpp.s
.PHONY : src/infrastructure/command/move/Mv2MemCommand.s

# target to generate assembly for a file
src/infrastructure/command/move/Mv2MemCommand.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu_simulation.dir/build.make CMakeFiles/cpu_simulation.dir/src/infrastructure/command/move/Mv2MemCommand.cpp.s
.PHONY : src/infrastructure/command/move/Mv2MemCommand.cpp.s

src/infrastructure/command/move/Mv2RegCommand.o: src/infrastructure/command/move/Mv2RegCommand.cpp.o
.PHONY : src/infrastructure/command/move/Mv2RegCommand.o

# target to build an object file
src/infrastructure/command/move/Mv2RegCommand.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu_simulation.dir/build.make CMakeFiles/cpu_simulation.dir/src/infrastructure/command/move/Mv2RegCommand.cpp.o
.PHONY : src/infrastructure/command/move/Mv2RegCommand.cpp.o

src/infrastructure/command/move/Mv2RegCommand.i: src/infrastructure/command/move/Mv2RegCommand.cpp.i
.PHONY : src/infrastructure/command/move/Mv2RegCommand.i

# target to preprocess a source file
src/infrastructure/command/move/Mv2RegCommand.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu_simulation.dir/build.make CMakeFiles/cpu_simulation.dir/src/infrastructure/command/move/Mv2RegCommand.cpp.i
.PHONY : src/infrastructure/command/move/Mv2RegCommand.cpp.i

src/infrastructure/command/move/Mv2RegCommand.s: src/infrastructure/command/move/Mv2RegCommand.cpp.s
.PHONY : src/infrastructure/command/move/Mv2RegCommand.s

# target to generate assembly for a file
src/infrastructure/command/move/Mv2RegCommand.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu_simulation.dir/build.make CMakeFiles/cpu_simulation.dir/src/infrastructure/command/move/Mv2RegCommand.cpp.s
.PHONY : src/infrastructure/command/move/Mv2RegCommand.cpp.s

src/infrastructure/command/shift/ShlCommand.o: src/infrastructure/command/shift/ShlCommand.cpp.o
.PHONY : src/infrastructure/command/shift/ShlCommand.o

# target to build an object file
src/infrastructure/command/shift/ShlCommand.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu_simulation.dir/build.make CMakeFiles/cpu_simulation.dir/src/infrastructure/command/shift/ShlCommand.cpp.o
.PHONY : src/infrastructure/command/shift/ShlCommand.cpp.o

src/infrastructure/command/shift/ShlCommand.i: src/infrastructure/command/shift/ShlCommand.cpp.i
.PHONY : src/infrastructure/command/shift/ShlCommand.i

# target to preprocess a source file
src/infrastructure/command/shift/ShlCommand.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu_simulation.dir/build.make CMakeFiles/cpu_simulation.dir/src/infrastructure/command/shift/ShlCommand.cpp.i
.PHONY : src/infrastructure/command/shift/ShlCommand.cpp.i

src/infrastructure/command/shift/ShlCommand.s: src/infrastructure/command/shift/ShlCommand.cpp.s
.PHONY : src/infrastructure/command/shift/ShlCommand.s

# target to generate assembly for a file
src/infrastructure/command/shift/ShlCommand.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu_simulation.dir/build.make CMakeFiles/cpu_simulation.dir/src/infrastructure/command/shift/ShlCommand.cpp.s
.PHONY : src/infrastructure/command/shift/ShlCommand.cpp.s

src/infrastructure/command/shift/ShrArithCommand.o: src/infrastructure/command/shift/ShrArithCommand.cpp.o
.PHONY : src/infrastructure/command/shift/ShrArithCommand.o

# target to build an object file
src/infrastructure/command/shift/ShrArithCommand.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu_simulation.dir/build.make CMakeFiles/cpu_simulation.dir/src/infrastructure/command/shift/ShrArithCommand.cpp.o
.PHONY : src/infrastructure/command/shift/ShrArithCommand.cpp.o

src/infrastructure/command/shift/ShrArithCommand.i: src/infrastructure/command/shift/ShrArithCommand.cpp.i
.PHONY : src/infrastructure/command/shift/ShrArithCommand.i

# target to preprocess a source file
src/infrastructure/command/shift/ShrArithCommand.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu_simulation.dir/build.make CMakeFiles/cpu_simulation.dir/src/infrastructure/command/shift/ShrArithCommand.cpp.i
.PHONY : src/infrastructure/command/shift/ShrArithCommand.cpp.i

src/infrastructure/command/shift/ShrArithCommand.s: src/infrastructure/command/shift/ShrArithCommand.cpp.s
.PHONY : src/infrastructure/command/shift/ShrArithCommand.s

# target to generate assembly for a file
src/infrastructure/command/shift/ShrArithCommand.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu_simulation.dir/build.make CMakeFiles/cpu_simulation.dir/src/infrastructure/command/shift/ShrArithCommand.cpp.s
.PHONY : src/infrastructure/command/shift/ShrArithCommand.cpp.s

src/infrastructure/command/shift/ShrCommand.o: src/infrastructure/command/shift/ShrCommand.cpp.o
.PHONY : src/infrastructure/command/shift/ShrCommand.o

# target to build an object file
src/infrastructure/command/shift/ShrCommand.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu_simulation.dir/build.make CMakeFiles/cpu_simulation.dir/src/infrastructure/command/shift/ShrCommand.cpp.o
.PHONY : src/infrastructure/command/shift/ShrCommand.cpp.o

src/infrastructure/command/shift/ShrCommand.i: src/infrastructure/command/shift/ShrCommand.cpp.i
.PHONY : src/infrastructure/command/shift/ShrCommand.i

# target to preprocess a source file
src/infrastructure/command/shift/ShrCommand.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu_simulation.dir/build.make CMakeFiles/cpu_simulation.dir/src/infrastructure/command/shift/ShrCommand.cpp.i
.PHONY : src/infrastructure/command/shift/ShrCommand.cpp.i

src/infrastructure/command/shift/ShrCommand.s: src/infrastructure/command/shift/ShrCommand.cpp.s
.PHONY : src/infrastructure/command/shift/ShrCommand.s

# target to generate assembly for a file
src/infrastructure/command/shift/ShrCommand.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu_simulation.dir/build.make CMakeFiles/cpu_simulation.dir/src/infrastructure/command/shift/ShrCommand.cpp.s
.PHONY : src/infrastructure/command/shift/ShrCommand.cpp.s

src/infrastructure/io/input/StdInputReader.o: src/infrastructure/io/input/StdInputReader.cpp.o
.PHONY : src/infrastructure/io/input/StdInputReader.o

# target to build an object file
src/infrastructure/io/input/StdInputReader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu_simulation.dir/build.make CMakeFiles/cpu_simulation.dir/src/infrastructure/io/input/StdInputReader.cpp.o
.PHONY : src/infrastructure/io/input/StdInputReader.cpp.o

src/infrastructure/io/input/StdInputReader.i: src/infrastructure/io/input/StdInputReader.cpp.i
.PHONY : src/infrastructure/io/input/StdInputReader.i

# target to preprocess a source file
src/infrastructure/io/input/StdInputReader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu_simulation.dir/build.make CMakeFiles/cpu_simulation.dir/src/infrastructure/io/input/StdInputReader.cpp.i
.PHONY : src/infrastructure/io/input/StdInputReader.cpp.i

src/infrastructure/io/input/StdInputReader.s: src/infrastructure/io/input/StdInputReader.cpp.s
.PHONY : src/infrastructure/io/input/StdInputReader.s

# target to generate assembly for a file
src/infrastructure/io/input/StdInputReader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu_simulation.dir/build.make CMakeFiles/cpu_simulation.dir/src/infrastructure/io/input/StdInputReader.cpp.s
.PHONY : src/infrastructure/io/input/StdInputReader.cpp.s

src/infrastructure/io/output/StdOutputWriter.o: src/infrastructure/io/output/StdOutputWriter.cpp.o
.PHONY : src/infrastructure/io/output/StdOutputWriter.o

# target to build an object file
src/infrastructure/io/output/StdOutputWriter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu_simulation.dir/build.make CMakeFiles/cpu_simulation.dir/src/infrastructure/io/output/StdOutputWriter.cpp.o
.PHONY : src/infrastructure/io/output/StdOutputWriter.cpp.o

src/infrastructure/io/output/StdOutputWriter.i: src/infrastructure/io/output/StdOutputWriter.cpp.i
.PHONY : src/infrastructure/io/output/StdOutputWriter.i

# target to preprocess a source file
src/infrastructure/io/output/StdOutputWriter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu_simulation.dir/build.make CMakeFiles/cpu_simulation.dir/src/infrastructure/io/output/StdOutputWriter.cpp.i
.PHONY : src/infrastructure/io/output/StdOutputWriter.cpp.i

src/infrastructure/io/output/StdOutputWriter.s: src/infrastructure/io/output/StdOutputWriter.cpp.s
.PHONY : src/infrastructure/io/output/StdOutputWriter.s

# target to generate assembly for a file
src/infrastructure/io/output/StdOutputWriter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu_simulation.dir/build.make CMakeFiles/cpu_simulation.dir/src/infrastructure/io/output/StdOutputWriter.cpp.s
.PHONY : src/infrastructure/io/output/StdOutputWriter.cpp.s

src/infrastructure/logger/Logger.o: src/infrastructure/logger/Logger.cpp.o
.PHONY : src/infrastructure/logger/Logger.o

# target to build an object file
src/infrastructure/logger/Logger.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu_simulation.dir/build.make CMakeFiles/cpu_simulation.dir/src/infrastructure/logger/Logger.cpp.o
.PHONY : src/infrastructure/logger/Logger.cpp.o

src/infrastructure/logger/Logger.i: src/infrastructure/logger/Logger.cpp.i
.PHONY : src/infrastructure/logger/Logger.i

# target to preprocess a source file
src/infrastructure/logger/Logger.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu_simulation.dir/build.make CMakeFiles/cpu_simulation.dir/src/infrastructure/logger/Logger.cpp.i
.PHONY : src/infrastructure/logger/Logger.cpp.i

src/infrastructure/logger/Logger.s: src/infrastructure/logger/Logger.cpp.s
.PHONY : src/infrastructure/logger/Logger.s

# target to generate assembly for a file
src/infrastructure/logger/Logger.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu_simulation.dir/build.make CMakeFiles/cpu_simulation.dir/src/infrastructure/logger/Logger.cpp.s
.PHONY : src/infrastructure/logger/Logger.cpp.s

src/infrastructure/logger/LoggerFactory.o: src/infrastructure/logger/LoggerFactory.cpp.o
.PHONY : src/infrastructure/logger/LoggerFactory.o

# target to build an object file
src/infrastructure/logger/LoggerFactory.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu_simulation.dir/build.make CMakeFiles/cpu_simulation.dir/src/infrastructure/logger/LoggerFactory.cpp.o
.PHONY : src/infrastructure/logger/LoggerFactory.cpp.o

src/infrastructure/logger/LoggerFactory.i: src/infrastructure/logger/LoggerFactory.cpp.i
.PHONY : src/infrastructure/logger/LoggerFactory.i

# target to preprocess a source file
src/infrastructure/logger/LoggerFactory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu_simulation.dir/build.make CMakeFiles/cpu_simulation.dir/src/infrastructure/logger/LoggerFactory.cpp.i
.PHONY : src/infrastructure/logger/LoggerFactory.cpp.i

src/infrastructure/logger/LoggerFactory.s: src/infrastructure/logger/LoggerFactory.cpp.s
.PHONY : src/infrastructure/logger/LoggerFactory.s

# target to generate assembly for a file
src/infrastructure/logger/LoggerFactory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu_simulation.dir/build.make CMakeFiles/cpu_simulation.dir/src/infrastructure/logger/LoggerFactory.cpp.s
.PHONY : src/infrastructure/logger/LoggerFactory.cpp.s

src/infrastructure/store/MemoryStore.o: src/infrastructure/store/MemoryStore.cpp.o
.PHONY : src/infrastructure/store/MemoryStore.o

# target to build an object file
src/infrastructure/store/MemoryStore.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu_simulation.dir/build.make CMakeFiles/cpu_simulation.dir/src/infrastructure/store/MemoryStore.cpp.o
.PHONY : src/infrastructure/store/MemoryStore.cpp.o

src/infrastructure/store/MemoryStore.i: src/infrastructure/store/MemoryStore.cpp.i
.PHONY : src/infrastructure/store/MemoryStore.i

# target to preprocess a source file
src/infrastructure/store/MemoryStore.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu_simulation.dir/build.make CMakeFiles/cpu_simulation.dir/src/infrastructure/store/MemoryStore.cpp.i
.PHONY : src/infrastructure/store/MemoryStore.cpp.i

src/infrastructure/store/MemoryStore.s: src/infrastructure/store/MemoryStore.cpp.s
.PHONY : src/infrastructure/store/MemoryStore.s

# target to generate assembly for a file
src/infrastructure/store/MemoryStore.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu_simulation.dir/build.make CMakeFiles/cpu_simulation.dir/src/infrastructure/store/MemoryStore.cpp.s
.PHONY : src/infrastructure/store/MemoryStore.cpp.s

src/infrastructure/store/RegisterStore.o: src/infrastructure/store/RegisterStore.cpp.o
.PHONY : src/infrastructure/store/RegisterStore.o

# target to build an object file
src/infrastructure/store/RegisterStore.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu_simulation.dir/build.make CMakeFiles/cpu_simulation.dir/src/infrastructure/store/RegisterStore.cpp.o
.PHONY : src/infrastructure/store/RegisterStore.cpp.o

src/infrastructure/store/RegisterStore.i: src/infrastructure/store/RegisterStore.cpp.i
.PHONY : src/infrastructure/store/RegisterStore.i

# target to preprocess a source file
src/infrastructure/store/RegisterStore.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu_simulation.dir/build.make CMakeFiles/cpu_simulation.dir/src/infrastructure/store/RegisterStore.cpp.i
.PHONY : src/infrastructure/store/RegisterStore.cpp.i

src/infrastructure/store/RegisterStore.s: src/infrastructure/store/RegisterStore.cpp.s
.PHONY : src/infrastructure/store/RegisterStore.s

# target to generate assembly for a file
src/infrastructure/store/RegisterStore.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu_simulation.dir/build.make CMakeFiles/cpu_simulation.dir/src/infrastructure/store/RegisterStore.cpp.s
.PHONY : src/infrastructure/store/RegisterStore.cpp.s

src/infrastructure/store/Store.o: src/infrastructure/store/Store.cpp.o
.PHONY : src/infrastructure/store/Store.o

# target to build an object file
src/infrastructure/store/Store.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu_simulation.dir/build.make CMakeFiles/cpu_simulation.dir/src/infrastructure/store/Store.cpp.o
.PHONY : src/infrastructure/store/Store.cpp.o

src/infrastructure/store/Store.i: src/infrastructure/store/Store.cpp.i
.PHONY : src/infrastructure/store/Store.i

# target to preprocess a source file
src/infrastructure/store/Store.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu_simulation.dir/build.make CMakeFiles/cpu_simulation.dir/src/infrastructure/store/Store.cpp.i
.PHONY : src/infrastructure/store/Store.cpp.i

src/infrastructure/store/Store.s: src/infrastructure/store/Store.cpp.s
.PHONY : src/infrastructure/store/Store.s

# target to generate assembly for a file
src/infrastructure/store/Store.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu_simulation.dir/build.make CMakeFiles/cpu_simulation.dir/src/infrastructure/store/Store.cpp.s
.PHONY : src/infrastructure/store/Store.cpp.s

src/infrastructure/time/TimeService.o: src/infrastructure/time/TimeService.cpp.o
.PHONY : src/infrastructure/time/TimeService.o

# target to build an object file
src/infrastructure/time/TimeService.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu_simulation.dir/build.make CMakeFiles/cpu_simulation.dir/src/infrastructure/time/TimeService.cpp.o
.PHONY : src/infrastructure/time/TimeService.cpp.o

src/infrastructure/time/TimeService.i: src/infrastructure/time/TimeService.cpp.i
.PHONY : src/infrastructure/time/TimeService.i

# target to preprocess a source file
src/infrastructure/time/TimeService.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu_simulation.dir/build.make CMakeFiles/cpu_simulation.dir/src/infrastructure/time/TimeService.cpp.i
.PHONY : src/infrastructure/time/TimeService.cpp.i

src/infrastructure/time/TimeService.s: src/infrastructure/time/TimeService.cpp.s
.PHONY : src/infrastructure/time/TimeService.s

# target to generate assembly for a file
src/infrastructure/time/TimeService.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu_simulation.dir/build.make CMakeFiles/cpu_simulation.dir/src/infrastructure/time/TimeService.cpp.s
.PHONY : src/infrastructure/time/TimeService.cpp.s

src/infrastructure/unit/ControlUnit.o: src/infrastructure/unit/ControlUnit.cpp.o
.PHONY : src/infrastructure/unit/ControlUnit.o

# target to build an object file
src/infrastructure/unit/ControlUnit.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu_simulation.dir/build.make CMakeFiles/cpu_simulation.dir/src/infrastructure/unit/ControlUnit.cpp.o
.PHONY : src/infrastructure/unit/ControlUnit.cpp.o

src/infrastructure/unit/ControlUnit.i: src/infrastructure/unit/ControlUnit.cpp.i
.PHONY : src/infrastructure/unit/ControlUnit.i

# target to preprocess a source file
src/infrastructure/unit/ControlUnit.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu_simulation.dir/build.make CMakeFiles/cpu_simulation.dir/src/infrastructure/unit/ControlUnit.cpp.i
.PHONY : src/infrastructure/unit/ControlUnit.cpp.i

src/infrastructure/unit/ControlUnit.s: src/infrastructure/unit/ControlUnit.cpp.s
.PHONY : src/infrastructure/unit/ControlUnit.s

# target to generate assembly for a file
src/infrastructure/unit/ControlUnit.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpu_simulation.dir/build.make CMakeFiles/cpu_simulation.dir/src/infrastructure/unit/ControlUnit.cpp.s
.PHONY : src/infrastructure/unit/ControlUnit.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... cpu_simulation"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/domain/arith/ArithUnit.o"
	@echo "... src/domain/arith/ArithUnit.i"
	@echo "... src/domain/arith/ArithUnit.s"
	@echo "... src/domain/logic/LogicUnit.o"
	@echo "... src/domain/logic/LogicUnit.i"
	@echo "... src/domain/logic/LogicUnit.s"
	@echo "... src/domain/move/MoveUnit.o"
	@echo "... src/domain/move/MoveUnit.i"
	@echo "... src/domain/move/MoveUnit.s"
	@echo "... src/domain/shift/ShiftUnit.o"
	@echo "... src/domain/shift/ShiftUnit.i"
	@echo "... src/domain/shift/ShiftUnit.s"
	@echo "... src/framework/CommandHandler.o"
	@echo "... src/framework/CommandHandler.i"
	@echo "... src/framework/CommandHandler.s"
	@echo "... src/infrastructure/command/arith/AddCommand.o"
	@echo "... src/infrastructure/command/arith/AddCommand.i"
	@echo "... src/infrastructure/command/arith/AddCommand.s"
	@echo "... src/infrastructure/command/arith/DivCommand.o"
	@echo "... src/infrastructure/command/arith/DivCommand.i"
	@echo "... src/infrastructure/command/arith/DivCommand.s"
	@echo "... src/infrastructure/command/arith/MulCommand.o"
	@echo "... src/infrastructure/command/arith/MulCommand.i"
	@echo "... src/infrastructure/command/arith/MulCommand.s"
	@echo "... src/infrastructure/command/arith/SubCommand.o"
	@echo "... src/infrastructure/command/arith/SubCommand.i"
	@echo "... src/infrastructure/command/arith/SubCommand.s"
	@echo "... src/infrastructure/command/logic/AndCommand.o"
	@echo "... src/infrastructure/command/logic/AndCommand.i"
	@echo "... src/infrastructure/command/logic/AndCommand.s"
	@echo "... src/infrastructure/command/logic/NotCommand.o"
	@echo "... src/infrastructure/command/logic/NotCommand.i"
	@echo "... src/infrastructure/command/logic/NotCommand.s"
	@echo "... src/infrastructure/command/logic/OrCommand.o"
	@echo "... src/infrastructure/command/logic/OrCommand.i"
	@echo "... src/infrastructure/command/logic/OrCommand.s"
	@echo "... src/infrastructure/command/logic/SltCommand.o"
	@echo "... src/infrastructure/command/logic/SltCommand.i"
	@echo "... src/infrastructure/command/logic/SltCommand.s"
	@echo "... src/infrastructure/command/move/LdimmCommand.o"
	@echo "... src/infrastructure/command/move/LdimmCommand.i"
	@echo "... src/infrastructure/command/move/LdimmCommand.s"
	@echo "... src/infrastructure/command/move/Mv2MemCommand.o"
	@echo "... src/infrastructure/command/move/Mv2MemCommand.i"
	@echo "... src/infrastructure/command/move/Mv2MemCommand.s"
	@echo "... src/infrastructure/command/move/Mv2RegCommand.o"
	@echo "... src/infrastructure/command/move/Mv2RegCommand.i"
	@echo "... src/infrastructure/command/move/Mv2RegCommand.s"
	@echo "... src/infrastructure/command/shift/ShlCommand.o"
	@echo "... src/infrastructure/command/shift/ShlCommand.i"
	@echo "... src/infrastructure/command/shift/ShlCommand.s"
	@echo "... src/infrastructure/command/shift/ShrArithCommand.o"
	@echo "... src/infrastructure/command/shift/ShrArithCommand.i"
	@echo "... src/infrastructure/command/shift/ShrArithCommand.s"
	@echo "... src/infrastructure/command/shift/ShrCommand.o"
	@echo "... src/infrastructure/command/shift/ShrCommand.i"
	@echo "... src/infrastructure/command/shift/ShrCommand.s"
	@echo "... src/infrastructure/io/input/StdInputReader.o"
	@echo "... src/infrastructure/io/input/StdInputReader.i"
	@echo "... src/infrastructure/io/input/StdInputReader.s"
	@echo "... src/infrastructure/io/output/StdOutputWriter.o"
	@echo "... src/infrastructure/io/output/StdOutputWriter.i"
	@echo "... src/infrastructure/io/output/StdOutputWriter.s"
	@echo "... src/infrastructure/logger/Logger.o"
	@echo "... src/infrastructure/logger/Logger.i"
	@echo "... src/infrastructure/logger/Logger.s"
	@echo "... src/infrastructure/logger/LoggerFactory.o"
	@echo "... src/infrastructure/logger/LoggerFactory.i"
	@echo "... src/infrastructure/logger/LoggerFactory.s"
	@echo "... src/infrastructure/store/MemoryStore.o"
	@echo "... src/infrastructure/store/MemoryStore.i"
	@echo "... src/infrastructure/store/MemoryStore.s"
	@echo "... src/infrastructure/store/RegisterStore.o"
	@echo "... src/infrastructure/store/RegisterStore.i"
	@echo "... src/infrastructure/store/RegisterStore.s"
	@echo "... src/infrastructure/store/Store.o"
	@echo "... src/infrastructure/store/Store.i"
	@echo "... src/infrastructure/store/Store.s"
	@echo "... src/infrastructure/time/TimeService.o"
	@echo "... src/infrastructure/time/TimeService.i"
	@echo "... src/infrastructure/time/TimeService.s"
	@echo "... src/infrastructure/unit/ControlUnit.o"
	@echo "... src/infrastructure/unit/ControlUnit.i"
	@echo "... src/infrastructure/unit/ControlUnit.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

